# Generated by Django 3.2.9 on 2021-11-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='xml',
            name='word',
            field=models.CharField(default='bloodroot', max_length=100),
            preserve_default=False,
        ),
    ]
