# Generated by Django 3.2.9 on 2021-11-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_xml_xml_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xml',
            name='xml_file',
            field=models.FileField(blank=True, max_length=500, upload_to=''),
        ),
    ]
